- name: add user to docker root user
  hosts: dev
  become: true  
#   vars:
# #    jenkins_hostname: jenkins.example.com
#     java_packages:
#       - openjdk-8-jdk
  tasks:
  - name: add user using import roles
    import_role:
      name: geerlingguy.docker
    vars:
      docker_users: 
      - "{{ ansible_ssh_user }}"
    
