- name: play with jinja filters
  hosts: dev1
  gather_facts: no
  vars:
    git_username: sganesh089
    git_pwd: abcd345
    git_repo: ["ALB-cognito", "test-app"]
    count_test: [5, 6, 6, 4]
  tasks:
  - name: test name-capitalize
    debug:
      msg: |
        original : {{ git_username }}
        with filters: {{ git_username | capitalize }}
  - name: test pwd-capitalize
    debug:
      msg: |
        original : {{ git_pwd }}
        with filters: {{ git_pwd | password_hash('sha512') }}
  - name: test repo length
    debug:
      msg: |
        original : {{ git_repo }}
        with filters: {{ git_repo | length }}
  - name: test add jinja
    debug:
      msg: |
        original : {{ count_test }}
        with filters: {{ count_test | sum }}
  - name: test add jinja
    debug:
      msg: |
        original : {{ count_test }}
        with filters: {{ count_test | max }}
