- name: install k8s in cluster
  hosts: cluster
  become: true
  tasks:
  - name: docker
    import_role:
      name: geerlingguy.docker
  - name: install k8
    import_role:
      name: geerlingguy.kubernetes
